name: Selenium Tests

on:
  push:
    branches: [ main, add-new-test ]
  pull_request:
    branches: [ main, add-new-test ]

jobs:
  selenium-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium Tests
        run: |
          python tests/test_login.py
          python tests/test_invalid_login.py  # 🆕 Run the new test
