name: Selenium Python Tests (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use your preferred version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: 'LATEST'  # Or match your Chrome version

    - name: Run Selenium tests
      run: |
        python test_login.py
